### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by d6u** [d6u/web-playground#1]
## Beta Features
- [x] Add live reloading BrowserSync
- [x] Add better logging
- [x] Add informative error messages
- [x] Add more pre/post-processors (DONE #2)
  - EJS, Jade, Swig
  - SCSS, Less, Stylus, Autoprefixer
  - Babel, CoffeeScript, TypeScript
- [x] Fix Autoprefixer deprecated warning
- [x] Add CSS base assets (reset, normalize) (DONE #3)
- [x] Option to not open browser automatically
- [x] Option to not live reloading
- [x] Option to use random port instead of 3000
- [ ] Option to enable sub-directories mode
- [x] Option to specify current directory
- [ ] Deploy bundled page using https://surge.sh/
- [ ] ~~Pass options to preprocessors, e.g. Babel ES7 features~~ (favor minimum configuration)
- [ ] ~~Travis CI - test installation against popular Node versions~~ (only support Node 4 and above from now)
## 1.0 Features
- [x] **Can require CommonJS module**
- [ ] **Comprehensive error page**
  - [ ] Normal errors, e.g. missing files
  - [x] Compiler errors, HTML, JS and CSS at the same time (#6)
- [ ] **Integrate live-reload, instead of using BrowserSync proxy**
- [x] **Random port**
- [ ] **Speeeeeeeeeeeeeeeeeeeeeeeeeeeeeeed**
- [x] **Testing**

**Comment by prometheansacrifice** [comment]
@d6u How would you like to implement support for `surge.sh`?

**Comment by d6u** [comment]
@prometheansacrifice To be honest, I'm not positive on it. I can't even open https://surge.sh/ today. I think the `--bundle` option will help you put your project on any static server easily. So there isn't any immediate need I can see.

**Comment by d6u** [comment]
@prometheansacrifice That being said, I'd still love to see some generic options, e.g. upload to S3 or any FTP server easily. I encourage anyone who think web-playground is helpful to create a PR. :smile:
